name: Envia versao para Google Play Console

on:
  workflow_dispatch:
  push:
    branches:
      - to_google_play

jobs:
  test-google-play-connection:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: 📋 Informações da Execução
        run: |
          echo "🌿 Branch atual: ${{ github.ref_name }}"
          PACKAGE_NAME=$(grep '^name:' pubspec.yaml | awk '{print $2}')
          echo "📦 Nome do pacote (pubspec): $PACKAGE_NAME"
          echo "🆔 App ID (Android): com.gusoliveira21.memoryflash"

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: temurin

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.38.5

      - name: Install dependencies
        run: |
          flutter clean
          flutter pub get

      - name: Setup Keystore
        run: |
          mkdir -p android
          printf '%s' "${{ secrets.KEYSTORE_BASE64 }}" | base64 -d > android/keystore.jks

      - name: Configure signing
        run: |
          mkdir -p android/app
          echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 -d > android/app/keystore.jks

      - name: Configure signing
        run: |
          cat > android/key.properties <<EOF
          storeFile=${{ github.workspace }}/android/app/keystore.jks
          storePassword=${{ secrets.KEYSTORE_PASSWORD }}
          keyAlias=${{ secrets.KEY_ALIAS }}
          keyPassword=${{ secrets.KEY_PASSWORD }}
          EOF

      - name: Build App Bundle
        run: flutter build appbundle --release --build-number=${{ github.run_number }}

      - name: Create Service Account JSON
        run: echo '${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}' > android/service-account.json

      - name: Testar Conexão e Upload
        id: test_connection
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJson: android/service-account.json
          packageName: com.gusoliveira21.memoryflash
          releaseFiles: build/app/outputs/bundle/release/app-release.aab
          track: internal
          status: completed

      - name: Resultado do Teste
        if: always()
        run: |
          if [ "${{ steps.test_connection.outcome }}" = "success" ]; then
            echo "🎉 CONEXÃO E UPLOAD REALIZADOS COM SUCESSO!"
          else
            echo "❌ Falha no processo. Verifique os logs acima."
            exit 1
          fi
